version: "3.3"

services:
  frontend:
    build:
      context: ./services/frontend
      dockerfile: Dockerfile
    volumes:
      - "./services/frontend:/app"
      - "/app/node_modules"
    ports:
      - 3000:3000
    environment:
      - NODE_ENV=development
    depends_on:
      - backend
    stdin_open: true
    tty: true
  backend:
    build:
      context: "./services/backend"
      dockerfile: Dockerfile
    volumes:
      - "./services/backend:/app"
    ports:
      - 5000:5000
    environment:
      - FLASK_ENV=development
      - DATABASE_URI=sqlite:////db/scores.db
